version: '3.9'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SignApp@12345"
    ports:
      - "1434:1433"
    healthcheck:  # API başlamazdan əvvəl baza hazır olana qədər gözlə
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "SignApp@12345" -C -Q "SELECT 1" || exit 1
      interval: 10s
      retries: 10
      start_period: 30s

  api:
    build: ./api/SignApp.API
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=SignAppDb;User Id=sa;Password=SignApp@12345;TrustServerCertificate=True;"
    depends_on:
      mssql:
        condition: service_healthy  # Baza hazır olandan sonra işə düş
    restart: on-failure

  ui:
    build: ./ui
    ports:
      - "3001:80"
    depends_on:
      - api
    restart: on-failure

volumes:
  mssql_data: